#!/bin/sh
#copyright 2013 <lutostag@gmail.com>
#this program is licensed under CC0
catalog=$HOME/play/guten/catalog.tsv

if [[ ! -f $catalog ]] ; then
    echo "Catalog not found!" 1>&2
    exit 3
fi

if [[ "$1" == update ]] ; then
    wget -O - https://gitorious.org/gutenpress/gutenpress/archive-tarball/master | tar -xzOf - gutenpress-gutenpress/catalog.tsv > $catalog
    exit $?
elif [[ "$1" == search ]] ; then
    awk 'BEGIN { IGNORECASE=1 } '"$2"' { print $0 }' <$catalog| tr '\t' '\n'
elif [[ "$1" == numbers ]] ; then
    awk 'BEGIN { IGNORECASE=1 } '"$(echo $2 | tr -s ' ' '\n' | sed 's_\([0-9]*\)_/001:\1\\t/\n||_' | sed -e '$ {d}' | tr '\n' ' ')"' { print $0 }' <$catalog| tr '\t' '\n'
elif [[ "$1" == get ]] ; then
    if [[ "$2" == epub || "$2" == mobi || "$2" == plucker.pdb || "$2" == qioo.jar || $2 == txt.utf8 ]] ; then
        list=""
        if [[ "$3" == search ]] ; then
            list=$(awk 'BEGIN { IGNORECASE=1 } '"$4"' { sub(/001:/,"",$1); print $1 }' <$catalog | tr '\t' '\n')
        elif [[ "$3" == numbers ]] ; then
            list=$(echo $4 | tr -s ' ' '\n')
        else
            echo "Wrong syntax" 1>&2
            exit 2
        fi
        exitnum=0
        for number in $list
        do
            url=$(echo $number | sed "s_\(.*\)_ftp://gutenberg.readingroo.ms/gutenberg/cache/generated/\1/pg\1.$2_")
            echo "STARTING DOWNLOAD FOR EBOOK #$number"
            wget -qc $url && echo -e "\tCOMPLETED DOWNLOAD FOR EBOOK #$number" || (echo -e "\tFAILED DOWNLOAD FOR EBOOK #$number"; exit 1)
            exitnum=$(($exitnum?1:$?))
        done
        exit $exitnum
    else
        echo "Wrong get type" 1>&2
        exit 2
    fi
else
    echo "Wrong syntax" 1>&2
    exit 2
fi
